import Head from "next/head";
import Image from "next/image";
import Sample from "../components/sample";
import Nav from "../components/navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Web 3.0 | A new chapter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>

      {/* <h1 className="text-3xl font-bold underline">
        Hello, This is next js boilerplate structure with tailwind
      </h1>
      <Sample /> */}
      <Nav />
    </div>
  );
}
